_wandb:
    value:
        cli_version: 0.25.0
        e:
            i6uh2lr5gxn8fg33mxt77qkt9zr06hs6:
                args:
                    - --regularizer_name
                    - WCRR_5by5by5_32
                codePath: training_wcrr.py
                codePathLocal: training_wcrr.py
                cpu_count: 60
                cpu_count_logical: 60
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "104030265344"
                        used: "60208738304"
                email: shamachrist7@gmail.com
                executable: /HOME1/users/personal/wacg/miniconda3/envs/PyTorch/bin/python
                git:
                    commit: 84c2fe9a128b11338fbb498d58d3763fd13e0068
                    remote: git@github.com:Shamachrist7/wcrr-noncartesian-3d-mri.git
                gpu: NVIDIA A40
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-7909160a-e6be-3923-0da6-0929fd571370
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-7a8e1440-526f-9fdc-6286-ba2a78451bfe
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-826b0469-1440-9ba2-2320-8d4b96a7d094
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-9d921031-e94e-6034-3a45-662b99ae6524
                host: rosenblatt
                memory:
                    total: "206077095936"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/mathe/lvhome20/users/personal/wacg/wcrr-noncartesian-3d-mri/training_wcrr.py
                python: CPython 3.12.2
                root: /home/mathe/lvhome20/users/personal/wacg/wcrr-noncartesian-3d-mri
                startedAt: "2026-03-02T14:59:08.363469Z"
                writerId: i6uh2lr5gxn8fg33mxt77qkt9zr06hs6
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.2
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
architecture:
    value: Multi-noise level WCRR_5by5by5_32
dataset:
    value: Calgary-Campinas
epochs:
    value: 100
exponential lr decay factor:
    value: 0.9772372209558107
lr:
    value: 0.01
